all: lecture

lecture: lecture.tex
	pdflatex lecture.tex

pdl-groupmtg-talk: pdl-groupmtg-talk.tex
	pdflatex pdl-groupmtg-talk.tex

clean:
	rm -f lecture.aux lecture.out lecture.log
veryclean:
	rm -f lecture.aux lecture.out lecture.log lecture.pdf

