#!/bin/bash
# Use with extreme caution.
# You will probably need to \definecolor several of these.

IFS='\n' 
while read line; do
	echo -n "\\texttt{"
	echo -n "$line" | sed 's/{/\\{/g' | sed 's/}/\\}/g' | sed 's/_/\\_/g' | sed 's/~/\\textasciitilde/g' | sed 's/ /~/g' | sed 's/^\t*//' | sed 's/%/\\%/g' | sed 's/&/\\\&/g' | \
		sed 's/\<fn\>/\\hilight{brown}{fn}/g' | \
		sed 's/\<do\>/\\hilight{brown}{do}/g' | \
		sed 's/\<for\>/\\hilight{brown}{for}/g' | \
		sed 's/\<let\>/\\hilight{brown}{let}/g' | \
		sed 's/\<mut\>/\\hilight{brown}{mut}/g' | \
		sed 's/\<if\>/\\hilight{brown}{if}/g' | \
		sed 's/\<impl\>/\\hilight{brown}{impl}/g' | \
		sed 's/\<const\>/\\hilight{brown}{const}/g' | \
		sed 's/\<send\>/\\hilight{brown}{send}/g' | \
		sed 's/\(\/\/.*\)/\\hilight{darkcyan}{\1}/g' | \
		sed 's/\<assert\>/\\hilight{red}{assert}/g' | \
		sed 's/\<main\>/\\hilight{olivegreen}{main}/g' | \
		sed 's/\<5\>/\\hilight{brickred}{5}/g' | \
		sed 's/\(".*"\)/\\hilight{brickred}{\1}/g' | \
		sed 's/\(\<\w*\>\)::/\\hilight{violet}{\1}::/g' | \
		sed 's/::/\\hilight{grey}{::}/g' | \
		sed 's/\(\w*!\)/\\hilight{blue}{\1}/g' | \
		cat
	echo "} \\\\"
done
